# Generated by Django 2.0.3 on 2019-06-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=30)),
                ('prize', models.FloatField()),
            ],
        ),
    ]
