# Generated by Django 2.0.3 on 2019-06-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='num_toppings',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
