# Generated by Django 2.0.3 on 2019-07-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('prize', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='menuitem',
            name='available_extras',
            field=models.ManyToManyField(to='orders.Extra'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='extras',
            field=models.ManyToManyField(to='orders.Extra'),
        ),
    ]
