# Generated by Django 2.0.3 on 2019-07-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20190714_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='available_extras',
        ),
        migrations.AddField(
            model_name='extra',
            name='menuitems',
            field=models.ManyToManyField(to='orders.MenuItem'),
        ),
    ]
