# Generated by Django 2.0.3 on 2019-07-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20190714_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='extras',
            field=models.ManyToManyField(blank=True, to='orders.Extra'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='toppings',
            field=models.ManyToManyField(blank=True, to='orders.Topping'),
        ),
    ]
