# Generated by Django 2.0.3 on 2019-07-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20190714_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='extras',
            field=models.ManyToManyField(to='orders.Extra'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='toppings',
            field=models.ManyToManyField(to='orders.Topping'),
        ),
    ]
